# These are supported funding model platforms

custom: ['https://www.fiverr.com/creativitas/create-mobile-website-design-for-you-with-single-page-app', 'https://www.fiverr.com/creativitas/create-mobile-website-design-for-you-with-single-page-app', 'https://www.hockeycomputindo.com/2010/12/blog-post.html','https://axcora.com/sourcecode/']
